<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="מנחם" name="tests.SearchAndAddProductsTest" tests="7" failures="1" timestamp="2022-05-12T10:31:07 IDT" time="279.263" errors="0">
  <testcase name="tc15_addAlreadyExistProduct" time="32.207" classname="tests.SearchAndAddProductsTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at tests.SearchAndAddProductsTest.tc15_addAlreadyExistProduct(SearchAndAddProductsTest.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc15_addAlreadyExistProduct -->
  <system-out/>
  <testcase name="tc16_addMultipleTypesProduct" time="49.854" classname="tests.SearchAndAddProductsTest"/>
  <system-out/>
  <testcase name="tc17_addMultipleTypesProduct" time="36.974" classname="tests.SearchAndAddProductsTest"/>
  <system-out/>
  <testcase name="tc12_tc13_tc14_addNewRegularProduct" time="40.555" classname="tests.SearchAndAddProductsTest"/>
  <system-out/>
  <testcase name="tc12_tc13_tc14_addNewRegularProduct" time="48.002" classname="tests.SearchAndAddProductsTest"/>
  <system-out/>
  <testcase name="tc11_AddProductFromSearch" time="39.375" classname="tests.SearchAndAddProductsTest"/>
  <system-out/>
  <testcase name="tc12_tc13_tc14_addNewRegularProduct" time="32.296" classname="tests.SearchAndAddProductsTest"/>
  <system-out/>
</testsuite> <!-- tests.SearchAndAddProductsTest -->
